### ISSUE TITLE
Mac M1でGUI版Emacsが起動できない

### ISSUE THREAD

**Issue by daddygongon** [yuu-1st/org_viewer_for_electron#1]
面白そうなappをありがとうございます．
最初に入れた時はうまく動いていたのですが，最近試してみると何故かうまく動きません．
ご教示いただければ助かります．
1. 起動の際に「開発元が不明なのでどうする」という警告が出ます．確か，一度システム環境設定から起動させると２度目は出なくなると認識していたのですが，何故でしょう．
2. 編集しようとした時にEmacsが立ち上がりません．システムエラーを吐いて死にます．

当方，BigSur 11.6で，M1チップです．よろしくお願いします．

**Comment by yuu-1st** [comment]
1. アプリケーションを移動・コピー・再インストール等を行うと、別のアプリケーションと認識され、再度表示されることがあります。
例えば、dmgファイル内で起動し、そのあとアプリケーションフォルダに移動した際はコピーのため、再度表示されます。
以上の操作を行なっていないか一度ご確認ください。
2. こちらの解決には多少時間を必要とする可能性があります。可能であれば、出力されたシステムエラーの提示をお願いいたします。

**Comment by daddygongon** [comment]
早速ありがとうございます．
1.は治りました．申し訳ありません．
2.は別送します．

**Comment by yuu-1st** [comment]
現状：
- M1 Macでパッケージ版を起動すると通常起動できるが、そこから編集ボタンを押し、GUI版Emacsの起動を試みると、Emacs側でエラーが発生する。アプリ側では「Emacsを起動できませんでした。」と表示され、エラー文章自体は表示されない。[^1]
- M1 Macで当リポジトリをcloneし、npm ci及びnpm startをして起動した場合は、GUI版のEmacsを起動することができる。
- M1 Macで当リポジトリを利用し、パッケージを生成した場合も、Emacs側で同等のエラーが発生する。

[^1]: エラーを表示されるコードは記述されており、該当メッセージの下に表示されるため、エラー自体は戻ってきていないと推測。

**Comment by yuu-1st** [comment]
現在のパッケージがintelバージョンを配布していることに気がつきました。
これにより、当アプリケーションがRosettaを使用して起動するため、内部でx86_64と認識され、GUI版Emacsがx86_64の起動を試みたと思われます。
GUI版Emacsのx86_64がM1のMacで起動しない原因は不明ですが、本趣旨では解決する必要がないと判断し、省略します。

次回バージョン0.4.0以降、配布バージョンをUniversalに変更し、Rosettaを利用せずに実行できるようになります。これにより、本不具合が解決すると思われます。
もし、0.4.0以降でも本現象が生じる場合、`/Application/org_viewer_for_electron.app`を右クリックし、「情報を見る」から「一般情報」→「Rosettaを使用して開く」がオフになっているか確認してください。
これでも解決しない場合は、別途issueを立てる必要があります。

**Comment by daddygongon** [comment]
正常に立ち上がりました．解決してよかったです．お疲れ様でした． ^_^
